# Generated by Django 4.1.4 on 2023-01-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='b_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
